export enum MotorcycleModel {
    STREET_TRIPLE = 'STREET_TRIPLE',
    TIGER_SPORT_660 = 'TIGER_SPORT_660',
    SPEED_TRIPLE = 'SPEED_TRIPLE',
    ROCKET_3 = 'ROCKET_3',
    TRIDENT = 'TRIDENT',
    BONNEVILLE = 'BONNEVILLE'
}