export enum UserRole {
    TRIUMPH_ADMIN = 'TRIUMPH_ADMIN',
    DEALER_EMPLOYEE = 'DEALER_EMPLOYEE',
    PARTNER_EMPLOYEE = 'PARTNER_EMPLOYEE',
    TECHNICIAN = 'TECHNICIAN',
    STOCK_MANAGER = 'STOCK_MANAGER',
    DRIVER = 'DRIVER'
}