export enum UserRole {
    TRIUMPH_ADMIN = 'TRIUMPH_ADMIN',
    DEALERSHIP_MANAGER = 'DEALERSHIP_MANAGER',
    DEALERSHIP_EMPLOYEE = 'DEALERSHIP_EMPLOYEE',
    DEALERSHIP_TECHNICIAN = 'DEALERSHIP_TECHNICIAN',
    DEALERSHIP_STOCK_MANAGER = 'DEALERSHIP_STOCK_MANAGER',
    COMPANY_MANAGER = 'COMPANY_MANAGER',
    COMPANY_DRIVER = 'COMPANY_DRIVER',
    CLIENT = 'CLIENT'
}