version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: triumph_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - triumph_network

  api:
      image: node:18
      container_name: triumph_api
      working_dir: /usr/src/app
      command: sh -c "npm install && npm run prisma:generate && npm run prisma:migrate && npx nest start --watch"
      ports:
        - '3000:3000'
      environment:
        - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
        - JWT_SECRET=${JWT_SECRET}
        - NODE_ENV=development
      volumes:
        - .:/usr/src/app
      depends_on:
        - postgres
      networks:
        - triumph_network

  frontend:
    container_name: triumph_frontend
    build: 
      context: .
      dockerfile: src/infrastructure/react/triumph-fleet-ui/Dockerfile
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules
      - /usr/src/app/src/infrastructure/react/triumph-fleet-ui/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - api
    networks:
      - triumph_network

networks:
  triumph_network:
    driver: bridge

volumes:
  postgres_data:
