export enum Permission {
    // Admin Système
    MANAGE_SYSTEM_CONFIG = 'MANAGE_SYSTEM_CONFIG',
    MANAGE_ALL_DEALERSHIPS = 'MANAGE_ALL_DEALERSHIPS',
    MANAGE_MAINTENANCE_INTERVALS = 'MANAGE_MAINTENANCE_INTERVALS',
    VIEW_ALL_DEALERSHIPS = 'VIEW_ALL_DEALERSHIPS',

    // Gestion des entreprises partenaires
    CREATE_PARTNER_COMPANY = 'CREATE_PARTNER_COMPANY',
    UPDATE_PARTNER_COMPANY = 'UPDATE_PARTNER_COMPANY',    // Nouvelle permission
    DEACTIVATE_PARTNER_COMPANY = 'DEACTIVATE_PARTNER_COMPANY',    // Nouvelle permission
    VIEW_PARTNER_COMPANY = 'VIEW_PARTNER_COMPANY',
    VIEW_COMPANY_EMPLOYEES = 'VIEW_COMPANY_EMPLOYEES',
    VIEW_COMPANY_ASSIGNED_MOTORCYCLES = 'VIEW_COMPANY_ASSIGNED_MOTORCYCLES',    
    
    // Gestion des utilisateurs
    MANAGE_ALL_USERS = 'MANAGE_ALL_USERS', 
    MANAGE_DEALERSHIP_USERS = 'MANAGE_DEALERSHIP_USERS',
    MANAGE_COMPANY_USERS = 'MANAGE_COMPANY_USERS',

    // Gestion des motos
    MANAGE_ALL_MOTORCYCLES = 'MANAGE_ALL_MOTORCYCLES',
    MANAGE_DEALERSHIP_MOTORCYCLES = 'MANAGE_DEALERSHIP_MOTORCYCLES',
    VIEW_COMPANY_MOTORCYCLES = 'VIEW_COMPANY_MOTORCYCLES',
    ASSIGN_MOTORCYCLES = 'ASSIGN_MOTORCYCLES',
    UPDATE_MOTORCYCLE_STATUS = 'UPDATE_MOTORCYCLE_STATUS',

    // Maintenance
    MANAGE_MAINTENANCE = 'MANAGE_MAINTENANCE',
    SCHEDULE_MAINTENANCE = 'SCHEDULE_MAINTENANCE',
    PERFORM_MAINTENANCE = 'PERFORM_MAINTENANCE',
    VIEW_MAINTENANCE_HISTORY = 'VIEW_MAINTENANCE_HISTORY',

    // Pièces détachées
    MANAGE_PARTS_CATALOG = 'MANAGE_PARTS_CATALOG',
    MANAGE_PARTS_INVENTORY = 'MANAGE_PARTS_INVENTORY',
    VIEW_PARTS_INVENTORY = 'VIEW_PARTS_INVENTORY',

    // Essais
    MANAGE_TEST_RIDES = 'MANAGE_TEST_RIDES',
    SCHEDULE_TEST_RIDE = 'SCHEDULE_TEST_RIDE',
    VALIDATE_TEST_RIDE = 'VALIDATE_TEST_RIDE',

    // Incidents
    REPORT_INCIDENT = 'REPORT_INCIDENT',
    MANAGE_INCIDENTS = 'MANAGE_INCIDENTS',
    VIEW_INCIDENTS = 'VIEW_INCIDENTS',

    // Statistiques
    VIEW_ALL_STATISTICS = 'VIEW_ALL_STATISTICS',
    VIEW_DEALERSHIP_STATISTICS = 'VIEW_DEALERSHIP_STATISTICS',
    VIEW_COMPANY_STATISTICS = 'VIEW_COMPANY_STATISTICS'
}

export type PermissionRequirement = Permission | Permission[];